name: Upload to S3
on:
  push:
    branches:
      - main # ブランチを 'main' に変更

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 最新のバージョンに更新
      - name: Deploy to S3
        run: aws s3 sync ./ s3://aws-s3-cicd --delete --exclude ".git/*" --exclude ".github/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # 秘密情報を設定
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 秘密情報を設定

